"""
Builds an offset-dated data.js + _points_data.json pair for testing the production-style
weather pipeline (real fixed dates, no shift_dates.py) while staying inside Open-Meteo's
~16-day forecast horizon.

Unlike shift_dates.py (TEST-only, rolls "Proloog = tomorrow" every hour via GitHub Action),
this is a manual, one-time tool: give it a real anchor date (real Proloog's actual calendar
date) and a target date (where you want Proloog to land for this test), and it shifts every
date in data.js by that fixed gap -- stage dates, campSchedule dates, and any embedded
(dd/mm)-style date references in schedule text fields -- then regenerates _points_data.json
to match, using each wxPoint's own "idx" field as the key (Start=0, VP1=1, VP2=2, Finish=3),
never array position, so it stays correct even for stages with a different point count
(Proloog has 3, most stages have 4).

Usage:
    python3 build_offset_test.py <target_proloog_date YYYY-MM-DD>

Example, run today (2026-08-22) wanting this week's arrival to land on today:
    python3 build_offset_test.py 2026-08-23
    -> computes the real gap between actual Proloog (2026-09-13) and 2026-08-23,
       applies that same gap to every date in the file, prints the offset used.

Reads data.js from the current directory, writes the shifted data.js and
_points_data.json back into the current directory. Does not touch index.html --
that file is never date-dependent and should not be regenerated by this tool.
"""
import json
import re
import sys
import datetime

ANCHOR_HOUR = {0: 8, 1: 11, 2: 14, 3: 16}  # rough per-index snapshot hour, keyed by idx


def shift_iso(iso, delta_days):
    dt = datetime.date.fromisoformat(iso)
    return (dt + datetime.timedelta(days=delta_days)).isoformat()


def build(target_proloog_str):
    target_proloog = datetime.date.fromisoformat(target_proloog_str)

    with open("data.js", encoding="utf-8") as f:
        raw = f.read()
    prefix = "var RIDE="
    d = json.loads(raw[len(prefix):].rstrip(";\n"))

    real_proloog = datetime.date.fromisoformat(d["stages"][0]["iso"])
    delta_days = (target_proloog - real_proloog).days

    print(f"Real Proloog:   {real_proloog} ({real_proloog.strftime('%A')})")
    print(f"Target Proloog: {target_proloog} ({target_proloog.strftime('%A')})")
    print(f"Offset applied: {delta_days:+d} days"
          + ("  (weekday preserved)" if delta_days % 7 == 0 else "  (WARNING: not a multiple of 7, weekday pattern will shift)"))

    # --- shift every stage date ---
    for s in d["stages"]:
        old_iso = s["iso"]
        s["iso"] = shift_iso(old_iso, delta_days)

    # --- shift every campSchedule date, and any embedded (dd/mm) references in its text ---
    old_isos = [row["iso"] for row in d["event"]["campSchedule"]]
    new_isos = [shift_iso(iso, delta_days) for iso in old_isos]
    old_dates = [datetime.date.fromisoformat(iso) for iso in old_isos]
    date_map = {
        f"{od.day}/{od.month}": f"{datetime.date.fromisoformat(ni).day}/{datetime.date.fromisoformat(ni).month}"
        for od, ni in zip(old_dates, new_isos)
    }
    for row, new_iso in zip(d["event"]["campSchedule"], new_isos):
        row["iso"] = new_iso
        for k in ("diner", "ontbijt", "start"):
            if row.get(k):
                pattern = re.compile(r"\((" + "|".join(re.escape(k2) for k2 in date_map) + r")\)")
                row[k] = pattern.sub(lambda m: "(" + date_map[m.group(1)] + ")", row[k])

    with open("data.js", "w", encoding="utf-8") as f:
        f.write(prefix + json.dumps(d, ensure_ascii=False) + ";")

    # --- regenerate _points_data.json to match, using each point's own idx field ---
    points = []
    for s in d["stages"]:
        for wx in s["wxPoints"]:
            idx = wx["idx"]
            points.append({
                "key": f"{s['num']}-{idx}",
                "lat": round(wx["lat"], 4),
                "lon": round(wx["lon"], 4),
                "ele": wx["ele"],
                "date": s["iso"],
                "hour": ANCHOR_HOUR[idx],
            })
    with open("_points_data.json", "w") as f:
        json.dump(points, f)

    print()
    print("Shifted stage dates:")
    for s in d["stages"]:
        print(f"  {s['num']} {s['it']}: {s['iso']}")
    print()
    print(f"Wrote data.js and _points_data.json ({len(points)} points)")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python3 build_offset_test.py <target_proloog_date YYYY-MM-DD>")
        sys.exit(1)
    build(sys.argv[1])
